// Personal info
export const ME = {
  name:      'Tomy F. Romero',
  title:     'Full-Stack Software Engineer',
  location:  'Ocala, Florida',
  email:     'tomyfletcher99@hotmail.com',
  github:    'https://github.com/tomyRomero',
  linkedin:  'https://www.linkedin.com/in/tomyromero/',
  portfolio: 'https://tomyromero.vercel.app',
  bio: `Full-stack engineer building home care software at MEDsys. I work across C#/.NET services, React frontends, and the SQL Server work behind scheduling, billing, and authorizations, and I like asking the right questions to get to the root of what's needed. Nights and weekends I ship my own projects end to end. UVI graduate, bilingual in English and Spanish. SQL nerd.`,
};

export const resumeFile = {
  href:     '/Tomy_Romero_Resume_Public.pdf',
  filename: 'Tomy_Romero_Resume.pdf',
};

// Skills
export const skills: Record<string, string[]> = {
  'Languages':    ['C#', 'JavaScript/TypeScript', 'SQL', 'HTML/CSS'],
  'Backend':      ['ASP.NET Core', 'REST APIs', 'API Design', 'Entity Framework', 'LINQ', 'SignalR', 'Authentication'],
  'Frontend':     ['React', 'React Native', 'Next.js', 'TanStack Query', 'Tailwind CSS', 'Accessibility'],
  'Data & Cloud': ['SQL Server', 'T-SQL', 'Database Design', 'Azure', 'AWS'],
  'Tools':        ['Git', 'Docker', 'CI/CD', 'Unit Testing', 'Integration Testing', 'xUnit'],
};

// What the About views lead with, each pointing at its Skills category
export const coreStack = [
  { name: 'C# / .NET',  area: 'Backend',  cat: 'Backend' },
  { name: 'React',      area: 'Frontend', cat: 'Frontend' },
  { name: 'SQL Server', area: 'Data',     cat: 'Data & Cloud' },
];
export const skillAnchor = (cat: string) => `skill-${cat.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;


// About photos
import tomy       from '../public/assets/tomyRomeroGrad.jpeg';
import uvi        from '../public/assets/uvi.jpeg';
import president  from '../public/assets/presidentUvi.jpeg';
import deanslist  from '../public/assets/deanslist.jpeg';
import scholarship from '../public/assets/scholarship.jpeg';
import uvilogo    from '../public/assets/uvi_icon.webp';
import sga        from '../public/assets/sga.jpeg';
import newyork    from '../public/assets/newyork.jpg';
import rhodeisland from '../public/assets/rhodeisland.jpg';
import fall       from '../public/assets/picnic.jpg';
import headshot   from '../public/assets/headshot.jpg';
import liberty    from '../public/assets/statue-of-liberty.jpg';
import stamford   from '../public/assets/stamford-ct.jpg';
import river      from '../public/assets/autumn-river.jpg';
import hallOfFame from '../public/assets/basketball-hall-of-fame.jpg';
import winter     from '../public/assets/winter-ct.jpg';

export const profilePhoto = headshot;

export const images = [
  { img: liberty,      title: 'Statue of Liberty',                                        alt: 'Tomy Romero at the Statue of Liberty' },
  { img: stamford,     title: 'Stamford, CT',                                             alt: 'Tomy Romero in Stamford, Connecticut' },
  { img: river,        title: 'Autumn River',                                             alt: 'A river in autumn' },
  { img: tomy,         title: 'Graduation',                                               alt: 'Tomy Romero at graduation' },
  { img: winter,       title: 'Winter in CT',                                             alt: 'A snowy park in Connecticut' },
  { img: newyork,      title: 'New York City',                                            alt: 'Picture of New York City' },
  { img: uvi,          title: 'University of the Virgin Islands',                         alt: 'University of the Virgin Islands' },
  { img: hallOfFame,   title: 'Basketball Hall of Fame',                                  alt: 'Tomy Romero at the Basketball Hall of Fame' },
  { img: president,    title: 'Picture with President of UVI',                            alt: 'Picture with President of University of the Virgin Islands' },
  { img: deanslist,    title: "Dean's List Reception",                                    alt: "Dean's List Reception" },
  { img: fall,         title: 'Fall Picnic',                                              alt: 'Fall Picnic' },
  { img: rhodeisland,  title: 'Rhode Island',                                             alt: 'Picture of Rhode Island' },
  { img: scholarship,  title: 'Scholarship Award',                                        alt: 'Scholarship Reception' },
  { img: uvilogo,      title: 'University of the Virgin Islands Logo',                    alt: 'University of the Virgin Islands logo' },
  { img: sga,          title: 'Student Government Association Junior Senator',             alt: 'Tomy Romero as SGA Junior Senator' },
];

// Project screenshots
// Generated by scripts/project-images.mjs from public/projects/<title>/.
// The first file is the card image.
import projectImages from './projectImages.json';

// framed: the image already includes its device (see-through corners)
// vivid: colorful enough to crop edge to edge (the Photos widget uses these)
export type Shot = { src: string; w: number; h: number; framed?: boolean; vivid?: boolean };
export const projectSlug = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
export const shotsFor = (title: string): Shot[] =>
  (projectImages as Record<string, Shot[]>)[projectSlug(title)] ?? [];
// Phone screenshots get a blurred backdrop instead of being cropped
export const isTallShot = (s?: Shot) => !!s && s.h > s.w * 1.15;
// "07-product-details.png" → "Product details"
export const shotLabel = (s: Shot) => {
  const name = s.src.split('/').pop()!.replace(/\.[a-z]+$/i, '').replace(/^\d+[-_ ]*/, '').replace(/[-_]+/g, ' ');
  return name.charAt(0).toUpperCase() + name.slice(1);
};

// Projects
export const projects = [
  {
    title:       'ArtifyMe',
    platform:    'mobile' as 'web' | 'mobile',
    emoji:       '🎨',
    tagline:     'AI paintings from your own sketches',
    status:      'shipped' as const,
    year:        '2026',
    techStack:   'React Native, Expo, ASP.NET Core, SQL Server, Python, Stable Diffusion',
    description: 'Mobile app that paints your sketches with Stable Diffusion and ControlNet, live, step by step.',
    link:        'https://github.com/tomyRomero/artifyme',
  },
  {
    title:       'StoreOperations',
    platform:    'web' as 'web' | 'mobile',
    emoji:       '🛒',
    tagline:     'An online store, and the console that runs it',
    status:      'shipped' as const,
    year:        '2026',
    techStack:   'Next.js, React, ASP.NET Core, SQL Server, Stripe',
    description: 'Online store platform with Stripe checkout and sales tax, guest orders, and a console to run and brand the store.',
    link:        'https://github.com/tomyRomero/StoreOperations',
  },
  {
    title:       'Sparks',
    platform:    'web' as 'web' | 'mobile',
    emoji:       '✨',
    tagline:     'A social network for creative ideas',
    status:      'shipped' as const,
    year:        '2026',
    techStack:   'Next.js, React, ASP.NET Core, SQL Server, SignalR',
    description: 'Social network for creative ideas, with AI drafting, threaded comments and live messaging.',
    link:        'https://github.com/tomyRomero/sparks',
  },
].map(p => ({ ...p, cover: shotsFor(p.title)[0] ?? null, image: shotsFor(p.title)[0]?.src ?? null }));

// Project details
// isLive shows the Live Demo buttons
export const projectDetails = [
  {
    title:       'Sparks',
    type:        'Full Stack Social Network with AI Drafting',
    tools: [
      '/assets/typescript.png', '/assets/next.webp', '/assets/reactjs.png',
      '/assets/tailwind.png', '/assets/dotnet.png', '/assets/sql.png',
      '/assets/docker.png',
    ],
    description: `Sparks is a social network for creative ideas: movie pitches, book plots, artwork, haiku and jokes, each with a card of its own. Draft one with AI, talk it over in threaded comments, and message other members live. The Next.js and React web app talks to an ASP.NET Core API on .NET 10 with SQL Server, which owns the data, sign-in, images and real-time events over SignalR. Google Gemini writes the drafts, Cloudflare Workers AI paints the pictures, and images stay private in Cloudflare R2.`,
    features: [
      'A card for each kind: a movie script on a dark screen under its poster, a book plot beside its cover',
      'AI drafting with Gemini, and pictures painted by Cloudflare Workers AI',
      'Live messaging over SignalR, with typing indicators, "Seen" receipts and shared sparks',
      'Threaded comments, likes that update everywhere at once, and grouped activity',
      'Sign-in built from scratch, with rotating refresh tokens, lockout and rate limits',
      'Search, follows, who\'s online, and dark mode throughout',
      'Integration tests against a real SQL Server, and browser tests with accessibility checks, run in CI',
    ],
    livelink:   'https://github.com/tomyRomero/sparks',
    githubrepo: 'https://github.com/tomyRomero/sparks',
    year:       '2026',
    isLive:     false,
  },
  {
    title: 'ArtifyMe',
    type:  'Full Stack Mobile App with AI Image Generation',
    tools: [
      '/assets/typescript.png', '/assets/reactjs.png', '/assets/expo.png',
      '/assets/dotnet.png', '/assets/sql.png', '/assets/python.png',
      '/assets/fastapi.png',
    ],
    description: `ArtifyMe turns a sketch into a painting. Draw on the canvas, say what it is, pick a style, and watch it painted step by step, following your lines. The Expo and React Native app talks to an ASP.NET Core API on .NET 10 with SQL Server, which runs each painting as a background job, so closing the app never loses one. A Python FastAPI service runs Stable Diffusion 1.5 with ControlNet on a cloud GPU, and images stay private in Cloudflare R2.`,
    features: [
      'Drawing canvas with pen, pencil and marker brushes, shapes, undo and redo',
      'A live preview of every step, then the painting compared with the sketch',
      'Eight styles, and a "How it was made" view with the outline, prompt and seed',
      'Background generation, with a push notification when the artwork is ready',
      'Rotating refresh tokens, a list of signed-in devices, Face ID sign-in and an app lock',
      'Dark mode, VoiceOver support and reduced motion throughout',
      'Automated tests across the app, API and image service, run in CI',
    ],
    livelink:   'https://github.com/tomyRomero/artifyme',
    githubrepo: 'https://github.com/tomyRomero/artifyme',
    year:       '2026',
    isLive:     false,
  },
  {
    title: 'StoreOperations',
    type:  'Full Stack E-Commerce Platform',
    tools: [
      '/assets/typescript.png', '/assets/reactjs.png', '/assets/next.webp',
      '/assets/dotnet.png', '/assets/sql.png', '/assets/stripe.svg',
      '/assets/docker.png',
    ],
    description: `StoreOps is an online store platform: a storefront for shoppers and a console for the people who run the store. Shoppers browse, search and check out with or without an account. Stripe takes the payment and works out the sales tax, and the order is created only once Stripe confirms it. Owners run orders, products, customers and newsletters from the console, and change the theme, logo, colors and home page with a live preview. Next.js and React sit in front of an ASP.NET Core API with SQL Server, which sends every email through an outbox.`,
    features: [
      'Stripe checkout with sales tax, for guests and accounts',
      'Order tracking, with an email at every step',
      'A console for orders, refunds, products, deals, customers and newsletters',
      'A theme and brand editor with a live preview, keeping any brand color readable',
      'Light and dark mode, keyboard and screen reader support, aiming for WCAG 2.2 AA',
      'Secure by default: cookie sessions, rate limits, lockouts and admin-only routes',
      'Integration tests against a real SQL Server, plus unit and end-to-end tests, run in CI',
    ],
    livelink:   'https://github.com/tomyRomero/StoreOperations',
    githubrepo: 'https://github.com/tomyRomero/StoreOperations',
    year:       '2026',
    isLive:     false,
  },
].map(p => ({ ...p, images: shotsFor(p.title).map(x => x.src) }));

// Experience
// tint picks each organization's color (components/mac/Native.tsx); start
// and end are 'YYYY-MM' and drive the timeline, end null means current.
export type Tint = 'teal' | 'orange' | 'violet' | 'blue' | 'amber';

export const experiences: {
  title: string; company: string; short: string; logo: string; tint: Tint;
  start: string; end: string | null; date: string; location: string;
  description: string[]; tech: string[];
}[] = [
  {
    title:   'Software Engineer I',
    company: 'MEDsys Software Solutions',
    short:   'MEDsys',
    logo:    'M',
    tint:    'teal' as Tint,
    start:   '2025-04',
    end:     null,
    date:    'April 2025 – Present',
    location: 'Remote',
    description: [
      'Develop and maintain full-stack features for a HIPAA-compliant platform serving multiple home care agencies, using C#, ASP.NET, JavaScript, and SQL Server.',
      'Build and enhance reporting tools, data entry forms, and billing and invoicing workflows for operational teams.',
      'Resolve production support tickets and bugs, working with QA to find root causes and propose solutions.',
      'Work with business stakeholders to turn operational needs into features, in an Agile environment using Jira and Confluence.',
    ],
    tech: ['C# .NET', 'SQL Server', 'JavaScript', 'ASP.NET Core', 'Jira'],
  },
  {
    title:    'Software Developer Intern',
    company:  'LocalChef',
    short:    'LocalChef',
    logo:     'LC',
    tint:     'orange' as Tint,
    start:    '2025-01',
    end:      '2025-04',
    date:     'January 2025 – April 2025',
    location: 'Remote',
    description: [
      'Developed features for a startup product as part of a small, fast-paced engineering team.',
      'Helped build user authentication and payment integration for the platform.',
    ],
    tech: ['React', 'AWS', 'MySQL', 'Stripe'],
  },
  {
    title:    'Software Developer Trainee',
    company:  'Revature',
    short:    'Revature',
    logo:     'R',
    tint:     'violet' as Tint,
    start:    '2024-06',
    end:      '2024-09',
    date:     'June 2024 – September 2024',
    location: 'Remote',
    description: [
      'Completed a structured Agile software development training program covering the full development lifecycle.',
      'Applied code quality practices including testing, continuous integration, and version control.',
    ],
    tech: ['C# .NET', 'React', 'MS SQL Server', 'Docker', 'CI/CD'],
  },
];

// Education
export const education = [
  {
    institution: 'University of the Virgin Islands',
    degree:      'Bachelor of Science',
    field:       'Computer Science',
    period:      'August 2018 – December 2022',
    location:    'St. Thomas, USVI',
    logo:        'UVI',
    tint:        'blue' as Tint,
    years:       '2018 – 2022',
    bullets: [
      'Student Government Association Junior Senator',
      "Dean's List recipient for multiple semesters",
    ],
  },
];

// Certifications
export const certifications = [
  {
    name:         'AWS Cloud Quest: Cloud Practitioner',
    issuer:       'Amazon Web Services (AWS)',
    logo:         'AWS',
    tint:         'amber' as Tint,
    issued:       'Apr 2026',
    credentialId: null,
    url:          'https://www.credly.com/badges/a3e1cf34-d475-4f11-a3a9-fd19e0038af7/public_url',
  },
  {
    name:         'Microsoft SQL Server Specialization',
    issuer:       'Microsoft',
    logo:         'MS',
    tint:         'blue' as Tint,
    issued:       'Feb 2026',
    credentialId: '7SIMAY3OEGQN',
    url:          'https://www.coursera.org/account/accomplishments/specialization/7SIMAY3OEGQN',
  },
  {
    name:         'AWS Academy Cloud Foundations',
    issuer:       'Amazon Web Services (AWS)',
    logo:         'AWS',
    tint:         'amber' as Tint,
    issued:       'Sep 2022',
    credentialId: null,
    url:          'https://www.credly.com/badges/49f35d3b-7ea8-40ee-afde-77c8e7725827',
  },
];

// Contact
export const contactDetails = [
  { type: 'Email',    icon: '✉️', value: 'tomyfletcher99@hotmail.com',       href: 'mailto:tomyfletcher99@hotmail.com',            cv: 'tomyfletcher99@hotmail.com' },
  { type: 'LinkedIn', icon: '🔗', value: 'Tomy F. Romero',                 href: 'https://www.linkedin.com/in/tomyromero/', cv: 'https://www.linkedin.com/in/tomyromero/' },
  { type: 'GitHub',   icon: '⑂',  value: 'github.com/tomyRomero',            href: 'https://github.com/tomyRomero',                cv: 'https://github.com/tomyRomero' },
  { type: 'Location', icon: '📍', value: 'Ocala, Florida',              href: '',                                             cv: '' },
];

export const contactBlurb =
  'Want to talk shop about .NET, React, or SQL, or ask about one of my projects? Email is the fastest way to reach me.';
